#!/usr/bin/python
#-*-coding:utf-8-*-

'''
Created Date: May 15. 2020
Copyright: UNMAND SOLUTION
Author: Dae Jong Jin 
Description: Logitech joystick Serial Main Code
Revise : 270 line in key_reader.py --> IndexError (reconnect에서 pass로 수정)
'''

import sys, os, time, threading
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from umd_serial import UMDSerial


def main():
    print ("joystick serial v 1.0.0")

    str = """
    Commands:
        python3 umd_serial.py -t True
    """
    if len(sys.argv) == 1:
        mode = False
    else:
        if sys.argv[1] == '-h':
            print(str)
            exit()
        elif sys.argv[1] == '-t':
            if sys.argv[2] == "True":
                mode = True
            else:
                mode = False
    # print(sys.argv[2])
    # print(mode)
    us = UMDSerial(mode)

    us.waitPort()

if __name__ == '__main__':
    main()
