#!/usr/bin/python
#-*-coding:utf-8-*-

'''
Created Date: May 15. 2020
Copyright: UNMAND SOLUTION
Author: Dae Jong Jin 
Description: Logitech joystick Serial Main Code
'''

import sys, os, time, threading
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from umd_serial import UMDSerial


def main():
    print ("joystick serial v 1.0.0")

    us = UMDSerial()
    us.waitPort()

if __name__ == '__main__':
    main()
